import type { Metadata } from "next";
import { Anton, Geist, Geist_Mono, Inter, Playfair_Display } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const interThin = Inter({
  variable: "--font-thin",
  subsets: ["latin"],
});

const didoneHead = Playfair_Display({
  variable: "--font-didone",
  subsets: ["latin"],
});

const condensedHead = Anton({
  variable: "--font-condensed",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${interThin.variable} ${didoneHead.variable} ${condensedHead.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
